version: 2
jobs:
  generate_and_test:
    docker:
      - image: holochain/holonix:latest

    steps:
      - checkout
      - restore_cache:
          key: -V2-cc_tuts
      - run:
          name: Get single_source 
          command: nix-shell https://holochain.love --run 'cargo install single_source' 
      - run:
          name: Pass through
          command: ./create_docs.sh
      - run:
          name: Run all tests
          command: nix-shell https://holochain.love --run './run_all_tests.sh' 
      - save_cache:
          key: -V2-cc_tuts
          paths:
            - "cc_tuts"
      - persist_to_workspace:
          root: .
          paths:
            - docs/*
            - build/docs/*
  
  test_release:
    docker:
      - image: holochain/holonix:latest
    steps:
      - checkout
      - run:
          name: Run all release tests
          command: ./nix_test_release.sh


  test_install:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - attach_workspace:
          at: . 
      - run:
          name: Get single_source 
          command: cargo install single_source
      - run:
          name: remove sandbox
          command:  sudo mkdir -p /nix /etc/nix && sudo chmod a+rwx /nix && sudo chmod a+rwx /etc/nix && sudo chown -R $USER:$USER /nix && sudo chown -R $USER:$USER /etc/nix && echo 'sandbox = false' > /etc/nix/nix.conf
      - run:
          name: Run all tests
          command: export USER=$(whoami) && ./test_install.sh

  test_install_mac:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run:
          name: Install Rust
          command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run:
          name: Get single_source 
          command: cargo install single_source
      - run:
          name: Run all tests
          command: export USER=$(whoami) && ./test_install_mac.sh

  build-mkdocs:
    docker:
      - image: squidfunk/mkdocs-material

    steps:
      - checkout
      - attach_workspace:
          at: . 
      - run:
          name: Build mkdocs 
          command: mkdocs build -d build/docs
      - persist_to_workspace:
          root: .
          paths:
            - docs/*
            - build/*
   
  release:
    docker:
          - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: . 
      - run:
          name: Install netlify-cli
          command: sudo npm install -g --silent netlify-cli
      - run:
          name: Netlify Deploy
          command: netlify deploy --prod --dir=build
          no_output_timeout: 300m

workflows:
  version: 2
  build_and_test:
    jobs:
      - generate_and_test:
          filters:
            branches:
              only: 
                - develop
                - master
      - test_install:
          filters:
            branches:
              only: 
                - develop
                - master
      - test_release:
          filters:
            branches:
              only: 
                - develop
