[package]
name = "regenerate_html_bin"
version = "0.1.0"
authors = ["Connor Turland <connor.turland@holo.host>"]
edition = "2018"

[dependencies]
handlebars = "1.1.0"
serde_json = "1.0.39"
chrono = "0.4.6"